# Generated by Django 4.2.7 on 2025-12-06 13:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LorryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lorry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='tracking.lorry')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
