# Generated by Django 4.2.7 on 2025-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_lorryroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='lorryroute',
            name='distance_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lorryroute',
            name='travel_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
